# Generated by Django 3.1 on 2020-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usersubscriber_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriber',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='usersubscriber',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
