# Generated by Django 3.1 on 2020-08-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200816_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriber',
            old_name='user',
            new_name='username',
        ),
    ]
